pipeline:
  deploy:
    image: appleboy/drone-ssh
    host: 111.231.81.213
    port: 22
    username: root
    password: Aa19960902
    command_timeout: 600
    script:
      - cd schedule_be
      - git pull
      - docker-compose build
      - docker-compose up -d