pipeline:
  deploy:
    image: appleboy/drone-ssh
    host: 111.231.81.213
    port: 22
    username: root
    password: Aa19960902
    command_timeout: 600
    script:
      - cd /home/ubuntu/Blog-Backup
      - git checkout -- ./
      - git pull
      - npm run build