# Header
menu:
  主页: /
  所有文章: /archives
  前端之路: /tags/前端
  管理学习: /tags/管理
  随笔杂文: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/Lxxyx"
  # weibo: "http://weibo.com/2239592792"
  rss: "/atom.xml"
  zhihu: "https://www.zhihu.com/people/Lxxyx"
  #douban: "#"
  mail: "mailto:Lxxyxzj@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: false

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-71744638-1'
favicon: /favicon.ico

#你的头像url
avatar: http://7xk109.com1.z0.glb.clouddn.com/blog-head.jpg
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: Lxxyx
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
# friends: false
friends:
  三省吾身丶丶: http://guowenfh.github.io/
  island的个人网站: http://www.zhibinnet.com/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 某211的纯文科生，2018年毕业。热爱前端与Node.js。在学校的网站工作室中担任前端开发的工作，有实际项目经验。将来想成为一名前端工程师。